### ISSUE TITLE
UDP Server

### ISSUE THREAD

**Issue by rothvann** [FRC3476/FRC-2017#36]
Implement a UDP server in both Java and C++ to communicate between the RIO and the Jetson. Currently we will be communicating through JSON but it may change in the future.

**Comment by saikiranra** [comment]
Why Python is GOAT

```python
from socket import *

serverSocket = socket(AF_INET, SOCK_DGRAM)
serverSocket.bind(('', 12000))

message, address = serverSocket.recvfrom(1024)
serverSocket.sendto("PASSBACK: " + message, address) 
```

```python
import time
from socket import *

for pings in range(10):
    clientSocket = socket(AF_INET, SOCK_DGRAM)
    clientSocket.settimeout(1)
    message = 'test'
    addr = ("127.0.0.1", 12000)

    start = time.time()
    clientSocket.sendto(message, addr)
    try:
        data, server = clientSocket.recvfrom(1024)
        end = time.time()
        elapsed = end - start
        print '%s %d %d' % (data, pings, elapsed)
    except timeout:
        print 'REQUEST TIMED OUT'
```

**Comment by SwampApe-Roth** [comment]
Well now that I look at it, 254 is using TCP instead of UDP. We can switch so if you had a choice would you go for TCP or UDP?

**Comment by SwampApe-Roth** [comment]
Also since UDP only has one thread receiving, how do game servers actually use UDP? Wouldn't the one thread running be a massive bottleneck?

**Comment by saikiranra** [comment]
UDP is used when you 
1) Care about speed
2) Can throw away packets

If you timestamp the packets, missed packets here and there shouldn't matter (theoretically) for vision stuff, but hey, you might see a problem when you actually implement it. I think you should stick with UDP right now, as it should be very easy to switch to TCP if you need to.

The threaded thing isn't a problem if you push the messages onto a queue and pop them when you need to read them. Since you are controlling when you send a packet and the queue, you shouldn't have a bottleneck unless you literally as many messages as you can as fast as possible and call a function each time you get a packet to handle it. If you read from the queue when you need it, you should be good.

**Comment by ThaHypnotoad** [comment]
Theres also thin abstractions over udp and tcp like rabbitmq and zeromq.
They give you cool things like pub sub.

**Comment by saikiranra** [comment]
Also looking at 971's code, it looks like they use TCP as well, but are current;y experimenting with UDP?

**Comment by SwampApe-Roth** [comment]
I think 971 is using UDP because 1678 is using UDP. You can bind and connect using the C API so that you can call recv instead of recvFrom.
